"""H1 topological loop data API.

Serves precomputed H1 cycle data for the frontend H1LoopNode.
Data lives at docs/sketches/h1-loop/data/ (gitignored, generated by
scripts/precompute_h1_cycles.py).
"""

import json
import logging
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/h1loop", tags=["h1loop"])

_DATA_DIRS: dict[str, Path] = {}
_MANIFESTS: dict[str, dict] = {}


def _find_data_dir(layer: str = "28") -> Path:
    suffix = "" if layer == "28" else f"_l{layer}"
    candidates = [
        Path(__file__).resolve().parent.parent.parent.parent.parent / "docs" / "sketches" / "h1-loop" / f"data{suffix}",
        Path("/app/docs/sketches/h1-loop") / f"data{suffix}",
    ]
    for c in candidates:
        if (c / "manifest.json").exists():
            return c
    raise FileNotFoundError(f"H1 loop data dir not found for layer {layer}")


def init_h1_data():
    for layer in ["28", "19"]:
        try:
            data_dir = _find_data_dir(layer)
            _DATA_DIRS[layer] = data_dir
            _MANIFESTS[layer] = json.loads((data_dir / "manifest.json").read_text())
            logger.info(
                "H1 loop data loaded: layer=%s, problems=%d, dir=%s",
                layer, len(_MANIFESTS[layer].get("problems", [])), data_dir,
            )
        except FileNotFoundError:
            logger.info("H1 loop data not found for layer %s (optional)", layer)


def _resolve_problem_path(idx: int, layer: str) -> Path:
    if layer not in _DATA_DIRS:
        raise HTTPException(404, f"No H1 data for layer {layer}")
    filepath = _DATA_DIRS[layer] / f"{idx:03d}.json"
    if not filepath.exists():
        raise HTTPException(404, f"Problem {idx} not found for layer {layer}")
    return filepath


@router.get("/manifest")
async def get_manifest(layer: str = "28") -> dict:
    if layer not in _MANIFESTS:
        raise HTTPException(404, f"No H1 data for layer {layer}")
    return _MANIFESTS[layer]


@router.get("/manifest/summary")
async def get_manifest_summary() -> dict:
    return {
        "available_layers": list(_MANIFESTS.keys()),
        "problems_per_layer": {k: len(v.get("problems", [])) for k, v in _MANIFESTS.items()},
        "schema_versions": {k: v.get("schema_version", "?") for k, v in _MANIFESTS.items()},
    }


@router.get("/problem/{idx}")
async def get_problem(idx: int, layer: str = "28"):
    filepath = _resolve_problem_path(idx, layer)
    return Response(content=filepath.read_bytes(), media_type="application/json")


@router.get("/problem/{idx}/lightweight")
async def get_problem_lightweight(idx: int, layer: str = "28") -> dict:
    filepath = _resolve_problem_path(idx, layer)
    data = json.loads(filepath.read_text())
    data.pop("distance_matrix_upper", None)
    data.pop("points_intermediate", None)
    return data


@router.get("/problem/{idx}/filtration")
async def get_problem_filtration(idx: int, layer: str = "28") -> dict:
    filepath = _resolve_problem_path(idx, layer)
    data = json.loads(filepath.read_text())
    return {
        "idx": data["idx"],
        "distance_matrix_upper": data.get("distance_matrix_upper", []),
        "n_subsampled": data.get("n_subsampled", 0),
    }
